name: Update Pictrs Images

on:
  schedule:
    - cron: '0 * * * *'  # Das Skript wird jede Stunde ausgeführt
  workflow_dispatch:  # Manuelle Ausführung auch möglich

jobs:
  scrape:
    runs-on: ubuntu-latest  # Führe den Job auf einer Ubuntu-VM aus

    steps:
    # Schritt 1: Checkout des Repositories
    - name: Checkout Repo
      uses: actions/checkout@v3

    # Schritt 2: Python einrichten
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # Verwende Python 3.11

    # Schritt 3: Abhängigkeiten installieren
    - name: Install Dependencies
      run: |
        pip install selenium==4.10.0
        pip install beautifulsoup4==4.11.1
        pip install --upgrade webdriver-manager

    # Schritt 4: Google Chrome installieren
    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable

    # Schritt 5: Führe das Python-Skript aus
    - name: Run the Scraper Script
      run: |
        python pictrs_scraper_all_images.py  # Ersetze dies mit dem tatsächlichen Pfad zu deinem Skript, wenn notwendig

    # Schritt 6: Änderungen committen und pushen
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add *.json  # Falls mehrere JSON-Dateien generiert werden
        git commit -m "Update galleries (automatisch via Action)" || echo "No changes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token für das Pushen der Änderungen
