name: Update Pictrs Galleries

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install selenium==4.10.0
        pip install beautifulsoup4==4.11.1
        pip install --upgrade webdriver-manager

    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable

    - name: Run the Scraper Script
      run: |
        python pictrs_scraper_gallery.py

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add *.json
        git commit -m "Update galleries (automatisch via Action)" || echo "No changes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
