name: Update Gallery JSON and Best-Of JSON

on:
  schedule:
    - cron: '0 * * * *'  # Jede Stunde
  workflow_dispatch:      # Manuelles Ausführen möglich

jobs:
  update-gallery-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run pictrs scraper
        run: python pictrs_scraper.py

      - name: Run pictrs scraper for best-of gallery
        run: python pictrs_scraper_best-of.py

      - name: Commit and push JSON files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Überprüfen, ob Änderungen vorliegen
          if git diff --quiet && git diff --staged --quiet; then
            echo "Keine Änderungen – nichts zu committen."
          else
            git add galerien.json
            git add gallerie_best-of.json
            git commit -m "Update galerien.json and gallerie_best-of.json"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
