name: Update Gallery JSON

on:
  schedule:
    - cron: "0 * * * *"  # Alle 1 Stunde
  workflow_dispatch:  # Möglichkeit, den Workflow manuell zu triggern

jobs:
  update-gallery-json:
    runs-on: ubuntu-latest

    steps:
      # Checkout des Repositories
      - name: Checkout code
        uses: actions/checkout@v2

      # Setzen der Python-Version
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Installiere die notwendigen Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Sicherstellen, dass das Verzeichnis korrekt ist
      - name: Check repository structure
        run: |
          ls -la  # Zeigt die Struktur des Repositories an

      # Wechsel in das Verzeichnis pictrs-gallery und führe das Skript aus
      - name: Run Pictrs Scraper
        run: |
          cd ..  # Gehe zum Hauptverzeichnis des Repositories (pictrs-gallery)
          ls -la  # Zeigt den Inhalt des Verzeichnisses an, um sicherzustellen, dass pictrs_scraper.py vorhanden ist
          python pictrs_scraper.py  # Führe das Skript aus

      # Commit und Push der geänderten 'galerien.json'
      - name: Commit and push updated gallery.json
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add galeries.json  # Sicherstellen, dass der Pfad korrekt ist
          git commit -m 'Update gallery.json'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token für automatische Commits und Pushes
